### ISSUE TITLE
Contribute a tile to the canvas 

### ISSUE THREAD

**Issue by bhaumikmistry** [bhaumikmistry/open-connect-art#1]
We want to have as many people as possible contribute a tile to the canvas on [open-connect-art](https://bhaumikmistry.github.io/open-connect-art/) and teach people how to contribute and take part in the [Hacktoberfest](https://hacktoberfest.digitalocean.com)

Take a look at the project README.md for more details.

**Comment by denz647** [comment]
The first issue
