### ISSUE TITLE
add 10px thick border to the full tile grid. Hacktoberfest2019

### ISSUE THREAD

**Issue by bhaumikmistry** [bhaumikmistry/open-connect-art#15]
Add 10px thick border to the full grid, that includes 10 columns which contains 10 rows.

We want to have as many people as possible contribute to open-connect-art and teach people how to contribute and take part in the Hacktoberfest

Take a look at the project's README.md for more details.

**Comment by snakedlover** [comment]
I would love to take this issue

**Comment by bhaumikmistry** [comment]
@snakedlover take a shot.

**Comment by bhaumikmistry** [comment]
@snakedlover update?
