### ISSUE TITLE
Split html file into three different file and folder, restructure webpage

### ISSUE THREAD

**Issue by bhaumikmistry** [bhaumikmistry/open-connect-art#19]
Restructure the cod. Move style/css code to css folder and html to be in index.html file and js code to js folder.

- [x] html change
- [x] css change
- [x] js change

at the end we should have 
```
-docs/
   |-src/
   |-css/
      |-style.css
   |-js/
      |-dark-mode.js
```

We want to have as many people as possible contribute to open-connect-art and teach people how to contribute and take part in the Hacktoberfest

Take a look at the project README.md for more details.

**Comment by PavanKKamra** [comment]
Hello Bhaumik, is possible for me to work on this issue? :).

**Comment by PavanKKamra** [comment]
Hello Bhaumik, 

I have made the changes and created a pull request for it. 

Thank you, 
Pavan K.
