### ISSUE TITLE
Display Contributor's name to the page.

### ISSUE THREAD

**Issue by bhaumikmistry** [bhaumikmistry/open-connect-art#23]
![test1](https://user-images.githubusercontent.com/17535720/66436699-c998bb80-e9f5-11e9-9042-c6ba73910f6e.PNG)
When we hover over the tiles the title of tile shows up. We want to disable the title there and make it display at a new location.
As shown in the attached image, the title of the Tile is the contributors name, so on hover the contributors name should show up below the logo and right of the text "contributor:"

- [ ] Add "Contributor:" text below the logo
- [ ] Disable title display on hover
- [ ] Enable title to show up after right of the newly added text and with "@" in front.

We want to have as many people as possible contribute to open-connect-art and teach people how to contribute and take part in the Hacktoberfest

Take a look at the project's README.md for more details.

**Comment by samanthakem** [comment]
I don't see an attached image here @bhaumikmistry, does it seem right? you mentioned it on your issue description.

**Comment by bhaumikmistry** [comment]
@samanthakem  Good catch. I have added the image. Thanks.

**Comment by bilalbutt044** [comment]
@bhaumikmistry  can i work on this?

**Comment by bhaumikmistry** [comment]
@samanthakem Please continue working if you are still working on it.

**Comment by samanthakem** [comment]
@bhaumikmistry I see that @bilalbutt044 has submitted a PR already so please move forward with him, if something changes, please let me know.
