### ISSUE TITLE
On hover change background of the tile to two different colors 

### ISSUE THREAD

**Issue by bhaumikmistry** [bhaumikmistry/open-connect-art#24]
We have dark mode now, So we would like to add different background color to the tile on hover on both modes. 

- [x] Set background color of tile on light mode to Aquamarine : 
   Colors that make up #7FFFD4
   W3C Color Name: Aquamarine
   RGB: 127, 255, 212 - HSL: 0.44, 1.00, 0.75
- [x] Set background color of tile on dark mode to Tickle Me Pink:
   Colors that make up #FF80AA 
   RGB: 255, 128, 170 - HSL: 0.94, 1.00, 0.75
   Web Safe Color: No

We want to have as many people as possible contribute to open-connect-art and teach people how to contribute and take part in the Hacktoberfest

Take a look at the project's README.md for more details.

**Comment by bilalbutt044** [comment]
I am working on it @bhaumikmistry
