### ISSUE TITLE
Add MIT license and badge

### ISSUE THREAD

**Issue by bhaumikmistry** [bhaumikmistry/open-connect-art#26]
- [ ] Add MIT license 
- [ ] Add badge for MIT license 

use: https://shields.io/category/license for badge info.

We want to have as many people as possible contribute to open-connect-art and teach people how to contribute and take part in the Hacktoberfest

Take a look at the project's README.md for more details.

**Comment by k4ch0** [comment]
I will work on it!

**Comment by bhaumikmistry** [comment]
@k4ch0 completed
