### ISSUE TITLE
Fork me on GitHub Ribbon

### ISSUE THREAD

**Issue by bhaumikmistry** [bhaumikmistry/open-connect-art#34]
Add Ribbon on right corner for Fork me on github.
use [Link](https://github.blog/2008-12-19-github-ribbons/) for reference 

- [x] Add ribbon 
- [ ] choose color to adapt with night view

We want to have as many people as possible contribute to open-connect-art and teach people how to contribute and take part in the Hacktoberfest

Take a look at the project's README.md for more details.

**Comment by DrMyuu** [comment]
Let me take a look

**Comment by DrMyuu** [comment]
Sent a PR on this issue.

**Comment by DrMyuu** [comment]
Any feedback?

**Comment by bhaumikmistry** [comment]
@DrMyuu Looks perfect, it works now, if you want to work on changing the color of from light to Dark for Light mode and dark mode you can work on it.
