### ISSUE TITLE
Change github corners color in Night mode and toggle 

### ISSUE THREAD

**Issue by bhaumikmistry** [bhaumikmistry/open-connect-art#35]
The color of github corner needs to change with the night mode toggle.

- [ ] update github corner to chagne colors. Helpful [like](http://tholman.com/github-corners/)

We want to have as many people as possible contribute to open-connect-art and teach people how to contribute and take part in the Hacktoberfest

Take a look at the project's README.md for more details.

**Comment by iman-sedgh** [comment]
Hi, May I work on it?

**Comment by khanaaziz1** [comment]
i want to contribute
