### ISSUE TITLE
Add Button to create dark mode for the web page

### ISSUE THREAD

**Issue by bhaumikmistry** [bhaumikmistry/open-connect-art#5]
Add a button to make the current web page into dark mode. 
- [x] make background turn dark
- [x] make all the text color to white 
- [x] convert pictures to inverted colors
- [x] use inverted pictures when user selects dark mode

We want to have as many people as possible contribute to open-connect-art and teach people how to contribute and take part in the Hacktoberfest

Take a look at the project's README.md for more details.

**Comment by KarlaChen** [comment]
Hi, @bhaumikmistry . Can I try it?

**Comment by bhaumikmistry** [comment]
@KarlaChen sure, go ahead. take care of all the points in to-do list.

**Comment by snakedlover** [comment]
@KarlaChen if you want can i also contribute ?

**Comment by KarlaChen** [comment]
@snakedlover sure. Go ahead.

**Comment by snakedlover** [comment]
Added the night mode option and done all the checkpoints also

**Comment by snakedlover** [comment]
Added the night mode option and done all the checkpoints also

**Comment by bhaumikmistry** [comment]
@snakedlover @KarlaChen Both made a good attempt. I'll work on both PR and merge it. Good work guys.
