### ISSUE TITLE
 Implement Refresh button for this issue.

### ISSUE THREAD

**Issue by bhaumikmistry** [bhaumikmistry/open-connect-art#61]
We have few buttons in the web-page which needs to be implemented.

Please Implement Refresh button for this issue.

- [ ] On select Refresh button change its color to yellow
- [ ] On select Refresh, refresh the webpage.

Take a look at the project's README.md for more details.

**Comment by MerlijnVH** [comment]
I wouldn't mind taking a look. :)

**Comment by MerlijnVH** [comment]
I made a PR for this issue. Technically the button does turn yellow when selecting it, but since it also refreshes the page, the effect is moot. :)
