### ISSUE TITLE
add logo to the main web page hactoberfest2019

### ISSUE THREAD

**Issue by bhaumikmistry** [bhaumikmistry/open-connect-art#7]
Add the openconnectart.png image to the web page along side the text image grid. The size should be not greater than 200*200, alignment and format is left for developers judgment.

We want to have as many people as possible contribute to open-connect-art and teach people how to contribute and take part in the Hacktoberfest

Take a look at the project README.md for more details.

**Comment by Sky0023** [comment]
@bhaumikmistry  can I do this issue?

**Comment by MrSoUndso** [comment]
Can I work on this? @bhaumikmistry

**Comment by matthewesp** [comment]
> Can I work on this? @bhaumikmistry

I submitted a pull request on this already.

**Comment by bhaumikmistry** [comment]
@matthewesp completed.
