### ISSUE TITLE
add Favico to the webpage.

### ISSUE THREAD

**Issue by bhaumikmistry** [bhaumikmistry/open-connect-art#81]
We would like to have a tiny Favicon updated to the wepage.

- [x] create a new folder in src/ name it favicon
- [x] download attached image 
![14285058911542186921-512](https://user-images.githubusercontent.com/17535720/67430592-8c652980-f5b0-11e9-8d27-bb0a471becd9.png)
- [x] copy this image to the new folder
- [x] follow steps to generate a html favicon package  https://realfavicongenerator.net/
- [x] Move the content of the package to newly created folder.
- [x] Insert the following code in the ```<head>``` section of html page:
```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff"> 
```
- [x] edit path 

> We want to have as many people as possible contribute a tile to the canvas on open-connect-art and teach people how to contribute and take part in the Hacktoberfest
> 
> Take a look at the project README.md for more details.

**Comment by hannah-saurusrex** [comment]
@bhaumikmistry I'd love to take a crack at this if it's available!

**Comment by hannah-saurusrex** [comment]
@bhaumikmistry I just created a pull request for this issue. It doesn't appear that there are any conflicts, but let me know if you have any questions.

Thanks!

**Comment by bhaumikmistry** [comment]
@hannah-saurusrex Great work.
